# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
app = "prism"
primary_region = "mia"

[env]
  PORT = "3000"
  NOSTR_RELAYS = "wss://nostrue.com,wss://relay.damus.io,wss://nos.lol,wss://nostr.wine,wss://relay.n057r.club,wss://relay.snort.social"

[mounts]
  source = "prism_data_v2"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
